### ISSUE TITLE
Future proposal Zigbee Scenes

### ISSUE THREAD

**Issue by MattWestb** [mdeweerd/zha_custom#1]
ZHA have not implanted / partly broken Scene and Groupe attribute and commands that is making it impossible adding real Zigbee scene in devices.

I have making request for fixing it in ZHA and Zigpy but the only comment is use services and adding (propriate) data.
As one no deep coding user its not possible doing that.

Z2M and deCONZ have it on place and its possible adding default scenes in IKEA lights and its working with IKEA scene remotes (Z2M oficaly and deCONZ not but i was doing it for over one year ago on my RaspBee I).

The syntax is not easy but its described in ZCL R7 and 8.

If its possible pleas implanting it in zha_custom so we can using native Zigbee scenes in our ZHA system with help of `zha_custom` services.

Thanks in advance !!!

Mattias W

**Comment by mdeweerd** [comment]
I have added the possibility to send "commands" to clusters.

I added examples in the documentation.  I tested "Store Scene" and "Recall Scene".  My device complained about it, but the frames were ok and decoded by 'tshark'.
Sending on/off commands worked with the samed device.

**Comment by MattWestb** [comment]
Im looking on it tomorrow !!

The large problem is add scene that is needed for adding scenes without light levels like IKEA is doing in there system for only changing the color of the light and not the brightness.
From my sniffing its need also some manufacturer commands being sent to the lights 2 for getting them stored as "relative scenes" but its coming later then can adding scenes to lights.

Zigpy is not having all frame parsing implanted so it can coming from the system is not liking the data and making it wrong but if you have sniffing it it shall being OK.


By the way great thanks for fixing the code so HA is loading it, now i can changing channel on my EZSP coordinators without re adding all devices :-)))

**Comment by MattWestb** [comment]
Try using view scene and you can see what the device have stored and if its looks OK then sniffing then its sending it to the system.

**Comment by mdeweerd** [comment]
I haven't investigated scenes a lot and I do not know if I need to add the device to the group first for instance or if I can set a scene without a group.
Maybe that was the issue.  The device complained when storing the scene and restoring it.  But the values and commands were decoded as expected.

If the commands are different from the defaults or not defined in the quirck, then I guess that this will not work as it uses the command information from the tables to determine how to send the command parameters.  
Adding the commands to the quirck should not be too complicated.

You can send commands with the manufacturer code, and that's also the case for writing attributes.  
The attributes do not rely on predefined lists, so you can send  the attributes and types that you want, but this implemenation of sending cluster commands does rely on the command lists.

To not rely on the command lists, there is a bit more work as a "raw" zcl command has to be set up.

**Comment by MattWestb** [comment]
It can being that the device dont like adding scenes if the group is not in the device.
But most lights is supporting the reserved group for _global scenes_ `0x0000` and shall normally being accepted.
The normal is first adding the group in the device and reading it so knowing its defined in the device and then adding scenes with the group  and reading the scenes so knowing they is OK in the device (the same scene number can being used in more groups and is being seperated in the device / group).

I think for the moment is raw command is the only way sending add scenes to light then ZHA/Zigpy have not implanting the parsing of the command if i have understanding it OK looking in the code in Ziggpy.

**Comment by mdeweerd** [comment]
IMHO add_scene is implemented and you need to provide the parameter as a string:
https://github.com/zigpy/zigpy/blob/a96523863f2d5fa9932daef59f85533caf99b25c/zigpy/zcl/clusters/general.py#L348

You need to provide three ints and a string (to indicate the attribute values I suppose - use yaml compatible escape codes for that).

**Comment by MattWestb** [comment]
I think Zigpy is not liking it then the extension feels sets is not defined in the code or im being wrong.
https://github.com/zigpy/zigpy/blob/db10b078874d93ad1c546ec810706c2e5dc33d7f/zigpy/zcl/clusters/general.py#L348-L353.

Extension field sets is the attributes from ZCL that you like being setted in the scene.

**Comment by mdeweerd** [comment]
But the comment says "# + extension field sets" and the string may be for the description of the scene.

So maybe that command needs special handling.  The extra arguments seem to be "serialized" which means they have to be of a known size.  Maybe a string will work, but otherwise it could be done so that when a list is provided for one of the "args" that this is added as an LVBytes class which would then be serialized as expected.

**Comment by mdeweerd** [comment]
> Extension field sets is the attributes from ZCL that you like being setted in the scene.

There is
https://github.com/zigpy/zigpy/blob/a96523863f2d5fa9932daef59f85533caf99b25c/zigpy/zcl/__init__.py#L161
and
https://github.com/zigpy/zigpy/blob/a96523863f2d5fa9932daef59f85533caf99b25c/zigpy/types/__init__.py#L14

which makes me think that the extra arguments may be serialized if they are accepted by the configuration of the command.

**Comment by mdeweerd** [comment]
I tried an 'Add scenes' likes this:
```yaml
service: zha_custom.execute
data:
  ieee: 5c:02:72:ff:fe:92:c2:5d
  command: zcl_cmd
  extra:
    cmd: 0
    cluster: 5
    endpoint: 11
    dir: 1
    args: [ 2, 5, 2, "Abc" ]
```

tshark indicated it's malformed:
```raw
ZigBee Cluster Library Frame
    Frame Control Field: Cluster-specific (0x01)
        .... ..01 = Frame Type: Cluster-specific (0x1)
        .... .0.. = Manufacturer Specific: False
        .... 0... = Direction: Client to Server
        ...0 .... = Disable Default Response: False
    Sequence Number: 29
    Command: Add Scene (0x00)
    Payload, String: Abc
        Group ID: 0x0002
        Scene ID: 0x05
        Transition Time: 2 seconds
        Length: 3
        String: Abc
[Malformed Packet: ZCL Scenes]
    [Expert Info (Error/Malformed): Malformed Packet (Exception occurred)]
        [Malformed Packet (Exception occurred)]
        [Severity level: Error]
        [Group: Malformed]
```

And the device was happy:
```raw
ZigBee Cluster Library Frame
    Frame Control Field: Cluster-specific (0x19)
        .... ..01 = Frame Type: Cluster-specific (0x1)
        .... .0.. = Manufacturer Specific: False
        .... 1... = Direction: Server to Client
        ...1 .... = Disable Default Response: True
    Sequence Number: 29
    Command: Add Scene Response (0x00)
    Payload
        Scenes Status: Success (0x00)
        Group ID: 0x0002
        Scene ID: 0x05
```

A fifth parameter in args was not accepted in the args parameters to the cluster's `command()` .

**Comment by mdeweerd** [comment]
I think the 'add scene' command needs at least an optional: https://github.com/zigpy/zigpy/blob/db10b078874d93ad1c546ec810706c2e5dc33d7f/zigpy/zcl/clusters/general.py#L376 .  Possibly it's not even 'optional' (because tshark says it's malformed) as a list of attributes may need to be provided - even an empty one.

**Comment by mdeweerd** [comment]
I managed to get this:
```raw
ZigBee Cluster Library Frame
    Frame Control Field: Cluster-specific (0x01)
        .... ..01 = Frame Type: Cluster-specific (0x1)
        .... .0.. = Manufacturer Specific: False
        .... 0... = Direction: Client to Server
        ...0 .... = Disable Default Response: False
    Sequence Number: 80
    Command: Add Scene (0x00)
    Payload, String: Abc
        Group ID: 0x0002
        Scene ID: 0x05
        Transition Time: 2 seconds
        Length: 3
        String: Abc
        Extension Set: 020102
```

by 'hacking' the definition of 'add scene'.

And by allowing a multibyte specification:
```yaml
```yaml
service: zha_custom.execute
data:
  ieee: 5c:02:72:ff:fe:92:c2:5d
  command: zcl_cmd
  extra:
    cmd: 0
    cluster: 5
    endpoint: 11
    dir: 1
    args: [ 2, 5, 2, "Abc", [1,2] ]
```

**Comment by mdeweerd** [comment]
Note that I just inverted the interpretation of 'dir' to be inline with the protocol.  So 'dir: 0' should be set in the examples above due to this change.

**Comment by MattWestb** [comment]
The extension feels is one or more attributes that shall being setted in the device scene.
One example IKEA remote is setting up scene 0x01 for group 0x002a with on/off, color light level and also blind position (IKEA manufacture blind cluster = set 4):

```
ZigBee Network Layer Data, Dst: 0xda58, Src: 0x0304
ZigBee Application Support Layer Data, Dst Endpt: 1, Src Endpt: 1
    Frame Control Field: Data (0x40)
    Destination Endpoint: 1
    Cluster: Scenes (0x0005)
    Profile: Home Automation (0x0104)
    Source Endpoint: 1
    Counter: 140
ZigBee Cluster Library Frame
    Frame Control Field: Cluster-specific (0x11)
        .... ..01 = Frame Type: Cluster-specific (0x1)
        .... .0.. = Manufacturer Specific: False
        .... 0... = Direction: Client to Server
        ...1 .... = Disable Default Response: True
    Sequence Number: 38
    Command: Add Scene (0x00)
    Payload, String: 
        Group ID: 0x002a
        Scene ID: 0x01
        Transition Time: 1 seconds
        Length: 0
        String: 
        Extension field set 1
            Cluster: On/Off (0x0006)
            On/Off: 1
        Extension field set 2
            Cluster: Color Control (0x0300)
            Color X: 0,5018
            Color Y: 0,4153
        Extension field set 3
            Cluster: Level Control (0x0008)
            Level: 25
        Extension field set 4
            Cluster: Unknown (0x0102)
            Current Position Lift Percentage: 0
            Current Position Tilt Percentage: 0
```
And device response:
```
IEEE 802.15.4 Data, Dst: 0x0304, Src: 0xda58
ZigBee Network Layer Data, Dst: 0x0304, Src: 0xda58
ZigBee Application Support Layer Data, Dst Endpt: 1, Src Endpt: 1
    Frame Control Field: Data (0x40)
    Destination Endpoint: 1
    Cluster: Scenes (0x0005)
    Profile: Home Automation (0x0104)
    Source Endpoint: 1
    Counter: 81
ZigBee Cluster Library Frame
    Frame Control Field: Cluster-specific (0x09)
        .... ..01 = Frame Type: Cluster-specific (0x1)
        .... .0.. = Manufacturer Specific: False
        .... 1... = Direction: Server to Client
        ...0 .... = Disable Default Response: False
    Sequence Number: 38
    Command: Add Scene Response (0x00)
    Payload
        Scenes Status: Success (0x00)
        Group ID: 0x002a
        Scene ID: 0x01
```
I think Z2M is using add scene with only one empty extension set or only one `on` then for getting the transition time and then using save scene that is updating all other attributes (the device is only updating new / changes attribute and transition time is not updated with save scene) fir getting saved scene with transition time in them.
I think its also putting the attribute in number order or its not working (if i remember Z2M implementation correct).

And then the remote is reading the scene for verifying it:
```
ZigBee Network Layer Data, Dst: 0xda58, Src: 0x0304
ZigBee Application Support Layer Data, Dst Endpt: 1, Src Endpt: 1
    Frame Control Field: Data (0x40)
    Destination Endpoint: 1
    Cluster: Scenes (0x0005)
    Profile: Home Automation (0x0104)
    Source Endpoint: 1
    Counter: 156
ZigBee Cluster Library Frame
    Frame Control Field: Cluster-specific (0x11)
        .... ..01 = Frame Type: Cluster-specific (0x1)
        .... .0.. = Manufacturer Specific: False
        .... 0... = Direction: Client to Server
        ...1 .... = Disable Default Response: True
    Sequence Number: 47
    Command: View Scene (0x01)
    Payload
        Group ID: 0x002a
        Scene ID: 0x01

```
And the response:
```
ZigBee Network Layer Data, Dst: 0x0304, Src: 0xda58
ZigBee Application Support Layer Data, Dst Endpt: 1, Src Endpt: 1
    Frame Control Field: Data (0x40)
    Destination Endpoint: 1
    Cluster: Scenes (0x0005)
    Profile: Home Automation (0x0104)
    Source Endpoint: 1
    Counter: 92
ZigBee Cluster Library Frame
    Frame Control Field: Cluster-specific (0x19)
        .... ..01 = Frame Type: Cluster-specific (0x1)
        .... .0.. = Manufacturer Specific: False
        .... 1... = Direction: Server to Client
        ...1 .... = Disable Default Response: True
    Sequence Number: 47
    Command: View Scene Response (0x01)
    Payload, String: 
        Scenes Status: Success (0x00)
        Group ID: 0x002a
        Scene ID: 0x01
        Transition Time: 1 seconds
        Length: 0
        String: 
        Extension field set 1
            Cluster: On/Off (0x0006)
            On/Off: 1
        Extension field set 2
            Cluster: Level Control (0x0008)
            Level: 25
        Extension field set 3
            Cluster: Color Control (0x0300)
            Color X: 0,5018
            Color Y: 0,4153
````
The remote is adding 3 scenes as is there default in IKEA lights.
The group is one random that is being made then the remote is joining the GW (its Zigbee Light Link so remotes is adding device and giving there address and group with touch link).
By adding  more scenes to the same group to the light its working with the remote scene changing keys both in Z2M and deCONZ.

**Comment by mdeweerd** [comment]
By default the command definition in Zigpy does not accept any extension attributes, so with normal use that definition has to be overwritten in the quirks.

What I did is override it in zha_custom by adding an optional parameter.  However I think It needs to be set to an LVList to not add the byte count at the start.

Then you have to set all required bytes for the extension fields.  For each cluster, the first two bytes are the cluster id, then the length, then the attribute values in the order they are defined in the ZCL Specification or according to the manufacturer.

**Comment by MattWestb** [comment]
## Thanks for looking on the problematic in ZHA / Zigpy !!

So what the ZHA /Zigpy devs have saying (using HA service and sending commands with data sets) is not working then extension set is not implanted in Zigpy (that i was expecting).
I have asking for one working example how to doing it but is being honored with deep silence from the dev team and saying is working as intended (= not working).

For normal user and more advances one with no deep coding knowledge its one no go then all is going down to bit manipulation and not zigbee commands / attributes (that is standard and understandable for my).

So my kitchen CT lights must is staying on the IKEA GW or i must "reactivating" my RaspBee I and running de(F)CONZ (im the only user deCONZ have black listed for one year ago in there GIT and forum then they dont like paying user asking for support for there payed devices) for getting it working then i dont have the coding knowledge or converting my production system to Z2M.

It was possible doing firmware downgrading and the firmware was restoring the 3 default scenes and getting some function in the system but i have not testing if its working after the last update of the firmware last month (IKEA was updating 85% of there light / driver).

Then is only hoping **puddly** is implanting it in his ZCL7 PR in Zigpy but i think its not interesting getting this part in place :-((

**Comment by mdeweerd** [comment]
Well, this is all open source and each type of developer has his priorities.  I am adding this to get to know zigpy a bit better and because I may have use for this in the future (sending a command without any other hassle may be handy).

I've tried several types to add the Extension field set, but I always get a length prefixed on the field which is then interpreted as the LSB of the first cluster id.  Other than that the contents of the Extension field set is ok.

So I asked as a zigpy "issue".

When the right way is found, the "Add scene" command can be called using a definition like this:

```yaml
service: zha_custom.execute
data:
  ieee: 5c:02:72:ff:fe:92:c2:5d
  command: zcl_cmd
  extra:
    cmd: 0
    cluster: 5
    endpoint: 11
    dir: 0
    args:
      - 2
      - 5
      - 2
      - Abc
      # Two bytes of cluster Id (LSB first), length, attribute value bytes
      - [0x06,0x00,1,1]
```

**Comment by mdeweerd** [comment]
So success after changing the type.

Now the example in my previous message results in :

![image](https://user-images.githubusercontent.com/1504752/148379501-07a4bdef-5b65-4d9d-a553-57869d4fa22e.png)

**Comment by mdeweerd** [comment]
When ok for you, please close this.

**Comment by MattWestb** [comment]
## That looks great !!
Can you explaining the `[0x06,0x00,1,1]` 0x06 = on/off cluster, 0x00 = ? 0x01 = on and last 0x01  is the first extension set.

Ops i was not reding !!
Cluster with LSB first so 0x00 is the first part of cluster 0x0006 !!

How to sending more extension set in one command ?
Adding more args like the last `- [0x06,0x00,1,1]` or is it needed changing more in the codblok before ?

**Comment by mdeweerd** [comment]
To send more than one, you have to "concatenate" them.

Suppose you want extension sets:
- [0x06,0x00,1,1]
And
- [0x08,0x00,2,6,5]

Then you need to put:
- [0x06,0x00,1,1,0x08,0x00,2,6,5]

Note: you can also write 6 and 8 in stead of 0x06 and 0x08, but I do it like that to remind me that they correspond to the cluster bytes and also because clusters are generally represented as a hex value.

**Comment by MattWestb** [comment]
OK and if one attribute is need more or lesser values the system is knowing it from the attribute on the cluster and its only "appending" more attributes in the args for the extension set.


I closing and testing later then i have getting my work finished i have starting (trying getting Linux on one STB box and running docker for installing RTL_433 and little more good things).


Great thanks !!!!

**Comment by mdeweerd** [comment]
The attributes accepted in the scenes are specified in the ZCL Specification.  Look for the sections with title "Scene Table Extensions" (as written in Table 3-41 of the ZCL).
An attribute that takes multiple bytes has the LSB first, but the order of the attributes is as listed.
